#!/bin/bash
set -eu
set -vx

function usage {
  echo "Usage: $0 <encrypted-file>"
}

if [[ $? -ne 1 ]]; then
  usage
  exit 1
fi
input_file=$1

function cleanup {
  rm -rf "$temp_file"
}
trap cleanup EXIT

temp_file=$(mktemp .ssh-secret-diary-XXXXXXX)
mktemp .ssh-secret-diary-XXXXXXX
EDITOR="${EDITOR:-vim}"

# Decrypt and edit
openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in "$input_file" > "$temp_file"
$EDITOR "$temp_file"

openssl rsautl -encrypt -inkey <(openssl rsa -in ~/.ssh/id_rsa -pubout) -pubin -in "$temp_file" > "$input_file"
